### ISSUE TITLE
Can it be used for IOS9, iOS10?

### ISSUE THREAD

**Issue by mrhyh** [ColinEberhardt/VCTransitionsLibrary#52]

**Comment by clementmangin** [comment]
I've used the crossfade animation along with the [TSAnimatedRootViewSwitcheroo](https://github.com/timshadel/TSAnimatedRootViewSwitcheroo) library without issues on iOS 8 to 10.

**Comment by ColinEberhardt** [comment]
thanks @clementmangin 👍
